# Gradle Properties
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Gradle Plugins
architectury_loom_version = 1.6.9999-PR.207+kneelawk

# Fabric Properties
# check these on https://fabricmc.net/develop
java_version = 21
minecraft_version = 1.20.6
mappings_version = 1
neoforge_patch = 1.20.5+build.3
fabric_loader_version = 0.15.10
neoforge_version = 20.6.12-beta

# Mod Properties
mod_version = 2.99.99+1.20.6.local
maven_group = com.kneelawk.graphlib
archives_base_name = graphlib

# Dependencies
fapi_version = 0.97.8+1.20.6
lns_version = 0.12.0-pre.2
kml_version = 0.3.0+1.20.6
knet_version = 0.3.0-beta.4+1.20.6

# Runtime Only Dependencies
mod_menu_version = 10.0.0-beta.1

# Javadoc Dependencies
jetbrains_annotations_version = 24.0.0
