modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mixins]]
config = "graphlib_net_util.mixins.json"

[[mods]]
modId = "graphlib_net_lib"
version = "${version}"
displayName = "GraphLib Networking Util"
authors = "Kneelawk"
description = "Networking utilities for GraphLib."
logoFile = "assets/graphlib/icon-128.png"

[[dependencies.graphlib_net_lib]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.4.148-beta,)"
ordering = "NONE"
side = "BOTH"
